
CREATE TABLE IF NOT EXISTS users(
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) UNIQUE,
  password_hash VARCHAR(255),
  nickname VARCHAR(100),
  balance DECIMAL(12,2) DEFAULT 0,
  is_admin TINYINT(1) DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS translations(
  id INT AUTO_INCREMENT PRIMARY KEY,
  lang VARCHAR(10),
  `key` VARCHAR(190),
  `value` TEXT,
  UNIQUE KEY uniq (lang, `key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
